import os


def _path(name):
    return os.path.abspath(os.path.join('assets', 'images', name))


BACKGROUND = _path('background.png')
SELECTION_ARROW = _path('selection_arrow.png')
START_GAME_BUTTON = _path('start_game_button.png')
HOW_TO_PLAY_BUTTON = _path('how_to_play_button.png')
CREDITS_BUTTON = _path('credits_button.png')

BRICK_WALL_BACKGROUND = _path('brick_wall_background.png')
GAUGE_BACKROUND = _path('gauge_background.png')
PLATE_EMOJI = _path('plate_emoji.png')
SHOWER_EMOJI = _path('shower_emoji.png')
TOILET_EMOJI = _path('toilet_emoji.png')
GAUGE_TYPE1_FILL1 = _path('gauge_type1_fill1.png')
GAUGE_TYPE1_FILL2 = _path('gauge_type1_fill2.png')
GAUGE_TYPE1_FILL3 = _path('gauge_type1_fill3.png')
GAUGE_TYPE1_FILL4 = _path('gauge_type1_fill4.png')
GAUGE_TYPE1_FILL5 = _path('gauge_type1_fill5.png')
GAUGE_TYPE2_FILL1 = _path('gauge_type2_fill1.png')
GAUGE_TYPE2_FILL2 = _path('gauge_type2_fill2.png')
GAUGE_TYPE2_FILL3 = _path('gauge_type2_fill3.png')
GAUGE_TYPE2_FILL4 = _path('gauge_type2_fill4.png')
GAUGE_TYPE2_FILL5 = _path('gauge_type2_fill5.png')
GAUGE_EMPTY = _path('gauge_empty.png')
GAUGE_VESSEL = _path('gauge_vessel.png')
GAME_CANVAS = _path('game_canvas.png')
MARBLE = _path('marble.png')

TILE_FLOOR = _path('tile_floor.png')
TILE_WALL = _path('tile_wall.png')
TILE_CHAR11 = _path('tile_char11.png')
TILE_CHAR12 = _path('tile_char12.png')
TILE_CHAR13 = _path('tile_char13.png')
TILE_CHAR21 = _path('tile_char21.png')
TILE_CHAR22 = _path('tile_char22.png')
TILE_CHAR23 = _path('tile_char23.png')
TILE_CHAR31 = _path('tile_char31.png')
TILE_CHAR32 = _path('tile_char32.png')
TILE_CHAR33 = _path('tile_char33.png')
TILE_CHAR41 = _path('tile_char41.png')
TILE_CHAR42 = _path('tile_char42.png')
TILE_CHAR43 = _path('tile_char43.png')
TILE_BEDSIDETABLE = _path('tile_bedsidetable.png')
TILE_BED_PART1 = _path('tile_bed_part1.png')
TILE_BED_PART2 = _path('tile_bed_part2.png')
TILE_TOILET_PART1 = _path('tile_toilet_part1.png')
TILE_TOILET_PART2 = _path('tile_toilet_part2.png')
TILE_BATHTUB_PART1 = _path('tile_bathtub_part1.png')
TILE_BATHTUB_PART2 = _path('tile_bathtub_part2.png')
TILE_WARDROBE_PART1 = _path('tile_wardrobe_part1.png')
TILE_WARDROBE_PART2 = _path('tile_wardrobe_part2.png')
TILE_WINDOW = _path('tile_window.png')
TILE_SMALL_TABLE_FLOWER = _path('tile_small_table_flower.png')
TILE_BATHROOM_MIRROR = _path('tile_bathroom_mirror.png')
TILE_BATHROOM_SINK = _path('tile_bathroom_sink.png')
TILE_TABLE_METAL_VERT = _path('tile_table_metal_vert.png')
TILE_TABLE_METAL_HORI = _path('tile_table_metal_hori.png')
TILE_OFFICE_CHAIR_LEFT = _path('tile_office_chair_left.png')
TILE_COUCH_PART1 = _path('tile_couch_part1.png')
TILE_COUCH_PART2 = _path('tile_couch_part2.png')
TILE_TABLE_BLACK_PART1 = _path('tile_table_black_part1.png')
TILE_TABLE_BLACK_PART2 = _path('tile_table_black_part2.png')
TILE_TELEVISION = _path('tile_television.png')
TILE_COUCH_VERT_PART1 = _path('tile_couch_vert_part1.png')
TILE_COUCH_VERT_PART2 = _path('tile_couch_vert_part2.png')
TILE_PADDED_ROUND_STOOL = _path('tile_padded_round_stool.png')
TILE_SHELF_BOOKS_PART1 = _path('tile_shelf_books_part1.png')
TILE_SHELF_BOOKS_PART2 = _path('tile_shelf_books_part2.png')
TILE_SHELF_BOOKS_PART3 = _path('tile_shelf_books_part3.png')
TILE_SHELF_BOOKS_PART4 = _path('tile_shelf_books_part4.png')
TILE_TELEPHONE = _path('tile_telephone.png')
TILE_TABLE = _path('tile_table.png')
TILE_SCULPTURE_BUST = _path('tile_sculpture_bust.png')
TILE_PAINTING_SUPPORT = _path('tile_painting_support.png')
TILE_ROUND_WOOD_STOOL = _path('tile_round_wood_stool.png')
TILE_LAMPSHADE = _path('tile_lampshade.png')
TILE_SHELF_BOOKS_SMALL_PART1 = _path('tile_shelf_books_small_part1.png')
TILE_SHELF_BOOKS_SMALL_PART2 = _path('tile_shelf_books_small_part2.png')
TILE_PLANT_PART1 = _path('tile_plant_part1.png')
TILE_PLANT_PART2 = _path('tile_plant_part2.png')
TILE_PLANT2_PART1 = _path('tile_plant2_part1.png')
TILE_PLANT2_PART2 = _path('tile_plant2_part2.png')
TILE_PLANT3 = _path('tile_plant3.png')
TILE_BALCONY = _path('tile_balcony.png')
TILE_BALCONY_FOOD_OVER = _path('tile_balcony_food_over.png')
TILE_BALCONY_STOVE = _path('tile_balcony_stove.png')
TILE_FRIDGE_PART1 = _path('tile_fridge_part1.png')
TILE_FRIDGE_PART2 = _path('tile_fridge_part2.png')
TILE_CHAIR_LEFT = _path('tile_chair_left.png')
TILE_CHAIR_RIGHT = _path('tile_chair_right.png')
TILE_CHAIR_UP = _path('tile_chair_up.png')
TILE_CHAIR_DOWN = _path('tile_chair_down.png')
TILE_TABLE_PART1 = _path('tile_table_part1.png')
TILE_TABLE_PART2 = _path('tile_table_part2.png')
TILE_TABLE_PART3 = _path('tile_table_part3.png')
TILE_SHELF_BREAD_PART1 = _path('tile_shelf_bread_part1.png')
TILE_SHELF_BREAD_PART2 = _path('tile_shelf_bread_part2.png')
TILE_SHELF_ITEMS_PART1 = _path('tile_shelf_items_part1.png')
TILE_SHELF_ITEMS_PART2 = _path('tile_shelf_items_part2.png')

TILE_FOOD_CAKE = _path('tile_food_cake.png')
TILE_FOOD_CAKE2 = _path('tile_food_cake2.png')
TILE_FOOD_FISH = _path('tile_food_fish.png')
TILE_FOOD_FRUITS = _path('tile_food_fruits.png')
TILE_FOOD_PIE = _path('tile_food_pie.png')
TILE_FOOD_PIG = _path('tile_food_pig.png')
TILE_FOOD_PIZZA = _path('tile_food_pizza.png')

BACKGROUND_EMPTY = _path('background_empty.png')
INTERACT_EXAMPLE = _path('interact_example.png')
MOVEMENT_EXAMPLE = _path('movement_example.png')
OBJECT_EXAMPLE = _path('object_example.png')
ESC_EXAMPLE = _path('esc_example.png')
SELECTION_BORDER = _path('selection_border.png')
ARROW_LEFT = _path('arrow_left.png')
ARROW_RIGHT = _path('arrow_right.png')

CREDITS = _path('credits.png')

ENDING = _path('ending.png')
CHECKMARK = _path('checkmark.png')
REPLAYARROW = _path('replayarrow.png')

TOILET_ICON = _path('toilet_icon.png')
